---
# defaults file for haproxy_pablo
#
#
haproxy_user: 'haproxy'
haproxy_group: 'haproxy'
haproxy_mode: 'http'
haproxy_chroot: '/var/lib/haproxy'

#Frontend settings
haproxy_bind_address: '10.0.2.15'
haproxy_bind_port: '80'

#Backend settings
haproxy_balance_mode: 'roundrobin'

#List of backend servers
haproxy_servers:
        - name: webserver1
          address: 192.168.10.2:80
        - name: webserver2
          address: 192.168.10.3:80
